name: Deploy

on:
  push:
    branches:
      - master
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare environment variables
        run:  |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          BASE_TAG="docker.pkg.github.com/hobroker/thyn:${BRANCH_NAME}"
          echo ::set-env name=BRANCH_NAME::${BRANCH_NAME}
          echo ::set-env name=TAG::$(echo ${BASE_TAG//:master/})
      - name: Build
        run: docker build . -t ${TAG}
      - name: Login to GitHub Docker Registry
        run: docker login docker.pkg.github.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Push
        run: |
          docker push ${TAG}
