name: Deploy

on:
  push:
    branches:
      - master
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare environment variables
        run:  |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          BASE_TAG="hobroker/thyn/thyn:${BRANCH_NAME}"
          BASE_TAG=$(echo ${BASE_TAG//:master/})
          echo ::set-env name=BRANCH_NAME::${BRANCH_NAME}
          echo ::set-env name=TAG::${BASE_TAG}
          echo ::set-env name=PUBLIC_TAG::"docker.pkg.github.com/${BASE_TAG}"
      - name: Login to GitHub Docker Registry
        run: |
          docker login https://docker.pkg.github.com --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
        env:
          DOCKER_USERNAME: hobroker
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          docker build . -t ${TAG}
          docker tag ${TAG} ${PUBLIC_TAG}
      - name: Push
        run: |
          docker push ${TAG}
