name: Deploy

on:
  push:
    branches:
      - master
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Extract branch name
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          TAG="${BASE_TAG}:${BRANCH}"

          echo "##[set-output name=branch;]$(echo ${BRANCH_NAME})"
          echo "##[set-output name=tag;]$(echo ${TAG//:master/})"
        id: base
        env:
          BASE_TAG: hobroker/thyn
      - name: Prepare .env
        run: |
          echo $COMPOSE_PROJECT_NAME
          cp "envs/${GITHUB_REF##*/}.env" .env
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> .env
#      - name: Down to hell
#        run: docker-compose down -v --remove-orphans
#      - name: Build
#        run: docker-compose build --compress --parallel
      - name: Up to heaven
        run: |
          echo ${{ steps.base.outputs.branch }}
          echo $TAG
        env:
          COMPOSE_PROJECT_NAME: thyn_${{ steps.base.outputs.branch }}
          TAG: ${{ steps.base.outputs.tag }}
#          docker-compose up -d --renew-anon-volumes
    env:
      DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
      NODE_ENV: production
