name: Deploy

on:
  push:
    branches:
      - master
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare environment variables
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          BASE_TAG="docker.pkg.github.com/hobroker/thyn/thyn:${BRANCH_NAME}"
          echo ::set-env name=BRANCH_NAME::${BRANCH_NAME}
          echo ::set-env name=TAG::$(echo ${BASE_TAG//:master/})
      - name: Login
        run: |
          docker login https://docker.pkg.github.com --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
        env:
          DOCKER_USERNAME: hobroker
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build . -t ${TAG}
      - name: Push
        run: docker push ${TAG}
