name: Deploy

on:
  push:
    branches:
      - master
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Prepare .env
        run: |
          echo $COMPOSE_PROJECT_NAME
          cp "envs/${GITHUB_REF##*/}.env" .env
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> .env
#      - name: Down to hell
#        run: docker-compose down -v --remove-orphans
#      - name: Build
#        run: docker-compose build --compress --parallel
#      - name: Up to heaven
#        run: docker-compose up -d --renew-anon-volumes
    env:
      DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
      NODE_ENV: production
      COMPOSE_PROJECT_NAME: "thyn_${GITHUB_REF##*/}"
